import {
  COMMON_COLORS,
  MAIN_DARK_THEME_COLORS,
  MAIN_LIGHT_THEME_COLORS,
  STATE_DARK_THEME_COLORS,
  STATE_LIGHT_THEME_COLORS,
  SURFACE_DARK_THEME_COLORS,
  SURFACE_LIGHT_THEME_COLORS,
  TEXT_DARK_THEME_COLORS,
  TEXT_LIGHT_THEME_COLORS,
} from './colorsConfig';

export const LIGHT_COLORS = {
  ...MAIN_LIGHT_THEME_COLORS,
  ...SURFACE_LIGHT_THEME_COLORS,
  ...TEXT_LIGHT_THEME_COLORS,
  ...STATE_LIGHT_THEME_COLORS,
} as const;

export const DARK_COLORS = {
  ...MAIN_DARK_THEME_COLORS,
  ...SURFACE_DARK_THEME_COLORS,
  ...TEXT_DARK_THEME_COLORS,
  ...STATE_DARK_THEME_COLORS,
} as const;

export const colors = {
  LIGHT_COLORS,
  DARK_COLORS,
  COMMON_COLORS,
};
