services:
  keycloak:
    build:
      context: ./keycloak-service
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://${KEYCLOAK_DB_HOST}:${KEYCLOAK_DB_PORT}/${KEYCLOAK_DB_NAME}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USERNAME}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL=${EMAIL}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - 8090:8080
    depends_on:
      - keycloak-db

  keycloak-db:
    image: 'postgres:15.4-bullseye'
    container_name: keycloak-db
    ports:
      - 5433:5432
    expose:
      - 5433
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USERNAME}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_DB=${KEYCLOAK_DB_NAME}
    volumes:
      - keycloak-db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wavvy-backend
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_LOCAL_URL}/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_SQL_INIT_MODE=always
      - SPRING_MAIL_HOST=${EMAIL_SMTP_HOST}
      - SPRING_MAIL_USERNAME=${EMAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${EMAIL_PASSWORD}
      - SPRING_MAIL_PORT=${EMAIL_SMTP_PORT}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_URL=${KEYCLOAK_LOCAL_URL}
      - SWAGGER_CLIENT_ID=${SWAGGER_CLIENT_ID}
      - SWAGGER_CLIENT_SECRET=${SWAGGER_CLIENT_SECRET}

  db:
    image: 'postgres:15.4-bullseye'
    container_name: db
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: wavvy-frontend
    ports:
      - 4200:80
    environment:
      - API_URL=http://localhost:8080
    depends_on:
      - backend
volumes:
  postgres:
  keycloak-db: