services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wavvy-backend
    ports:
      - 8080:8080
    expose:
      - 8080
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wavvy
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-update

#  db:
#    image: 'postgres:15.4-bullseye'
#    container_name: db
#    ports:
#      - 5432:5432
#    expose:
#      - 5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=wavvy
#    volumes:
#      - postgres:/var/lib/postgresql/data

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 4200:80
    environment:
      - API_URL=http://localhost:8080
    depends_on:
      - backend
#volumes:
#  postgres: