services:
  keycloak:
    build:
      context: ./keycloak-service
      dockerfile: Dockerfile
    container_name: keycloak
    restart: always
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://${KEYCLOAK_DB_HOST}/${KEYCLOAK_DB_NAME}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USERNAME}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL=${EMAIL}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DATABASE_LOCAL_URL=${DATABASE_LOCAL_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - BASE_URL=${BASE_URL}
      - SWAGGER_CLIENT_SECRET=${SWAGGER_CLIENT_SECRET}
      - KEYSTORE_PASSWORD=${KEY_STORE_PASSWORD}
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HOSTNAME_PATH=/keycloak
      - KC_PROXY=edge
      - KC_HOSTNAME_ADMIN_URL=https://wavvy.eu/keycloak
    ports:
      - 8090:8080
    expose:
      - 8090
    depends_on:
      - keycloak-db
      - db

  keycloak-db:
    image: 'postgres:15.4-bullseye'
    container_name: keycloak-db
    restart: always
    command: postgres -c max_prepared_transactions=200
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USERNAME}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_DB=${KEYCLOAK_DB_NAME}
    volumes:
      - /var/keycloak/data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wavvy-backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_LOCAL_URL}/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_SQL_INIT_MODE=never
      - SPRING_MAIL_HOST=${EMAIL_SMTP_HOST}
      - SPRING_MAIL_USERNAME=${EMAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${EMAIL_PASSWORD}
      - SPRING_MAIL_PORT=${EMAIL_SMTP_PORT}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_LOCAL_URL=${KEYCLOAK_LOCAL_URL}
      - SWAGGER_CLIENT_ID=${SWAGGER_CLIENT_ID}
      - IMAGES_BASE_URL=${IMAGES_BASE_URL}
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
      - SWAGGER_CLIENT_SECRET=${SWAGGER_CLIENT_SECRET}
      - API_URL=${API_URL}
      - API_PREFIX=${API_PREFIX}
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db

    volumes:
      - /var/images:/usr/share/wavvy/images

  db:
    image: 'postgres:15.4-bullseye'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - /var/postgres/data:/var/lib/postgresql/data

  pg-admin:
    image: 'dpage/pgadmin4:7.8'
    container_name: pg-admin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 81:80
    expose:
      - 81
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
        - KEYCLOAK_URL=${KEYCLOAK_URL}
        - KEYCLOAK_REALM=${KEYCLOAK_REALM}
        - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    container_name: wavvy-frontend
    restart: always
    ports:
      - 80:80
    expose:
      - 80
    environment:
      - API_URL=${API_URL}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    volumes:
      - /var/images:/usr/share/nginx/html/assets/images
