services:
  keycloak:
    build:
      context: ./keycloak-service
      dockerfile: Dockerfile
    container_name: keycloak
    restart: always
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://${KEYCLOAK_DB_HOST}/${KEYCLOAK_DB_NAME}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USERNAME}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL=${EMAIL}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DATABASE_LOCAL_URL=${DATABASE_LOCAL_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - KC_LOG_LEVEL=info
      - DEBUG=true
      - DEBUG_PORT=*:5005
    ports:
      - 30134:8080
      - 5005:5005
    expose:
      - 30134
    depends_on:
      - keycloak-db
      - db

  keycloak-db:
    image: 'postgres:15.4-bullseye'
    container_name: keycloak-db
    restart: always
    command: postgres -c max_prepared_transactions=200
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USERNAME}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_DB=${KEYCLOAK_DB_NAME}
    volumes:
      - /var/keycloak/data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wavvy-backend
    restart: always
    ports:
      - 20134:8080
    expose:
      - 20134
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_LOCAL_URL}/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_SQL_INIT_MODE=never
      - SPRING_MAIL_HOST=${EMAIL_SMTP_HOST}
      - SPRING_MAIL_USERNAME=${EMAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${EMAIL_PASSWORD}
      - SPRING_MAIL_PORT=${EMAIL_SMTP_PORT}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_LOCAL_URL=${KEYCLOAK_LOCAL_URL}
      - SWAGGER_CLIENT_ID=${SWAGGER_CLIENT_ID}
      - SWAGGER_CLIENT_SECRET=${SWAGGER_CLIENT_SECRET}
    volumes:
      - /var/images:/usr/share/wavvy/images

  db:
    image: 'postgres:15.4-bullseye'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - /var/postgres/data:/var/lib/postgresql/data

  pg-admin:
    image: 'dpage/pgadmin4:7.8'
    container_name: pg-admin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 40432:80
    expose:
      - 40432
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: wavvy-frontend
    restart: always
    ports:
      - 4200:80
    expose:
      - 4200
    environment:
      - API_URL=${API_URL}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    volumes:
      - /var/images:/usr/share/nginx/html/assets/images
