spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true
    host: smtp.poczta.onet.pl
    username: wavvy@op.pl
    password: Rcbsukcesja123$
    port: 465
  datasource:
    url: jdbc:postgresql://localhost:5432/wavvy
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          create_namespaces: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate: DEBUG