wavvy:
  images:
    logo:
      url: ${IMAGES_BASE_URL}/logo
    project:
      url: ${IMAGES_BASE_URL}/project
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${KEYCLOAK_LOCAL_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true
    host: ${EMAIL_SMTP_HOST}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: ${EMAIL_SMTP_PORT}
  datasource:
    url: ${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          create_namespaces: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:main-changelog.xml
    enabled: true
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    oauth:
      client-id: ${SWAGGER_CLIENT_ID}
      client-secret: ${SWAGGER_CLIENT_SECRET}
    display-request-duration: true
    url: /v3/api-docs
    path: /swagger-ui
    disable-swagger-default-url: true
    urls:
      - name: Wavvy API
        url: ${API_URL}/v3/api-docs
    config-url: ${API_PREFIX}/v3/api-docs/swagger-config
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate: DEBUG