spring:
  datasource:
    url: jdbc:h2:mem:dev-db
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
